### ISSUE TITLE
多分支流水线任务webhook设置

### ISSUE THREAD

**Issue by 0476** [jenkins-zh/jenkins-zh.github.io#15]
jenkins中创建多分支流水线任务，结合webhook进行自动化构建，想要对指定的分支如【master】配置接收webhook事件处理，应如何配置？或者需要什么特定的插件？

**Comment by LinuxSuRen** [comment]
首先，多分支流水线可以支持多个分支。我们假设有分支1，2，3。你说的指定分支，是希望只给分支1配置webhook吗？如果你不需要指定特定分支的话，对于GitHub而言，只要给你给定的账户有增加webhook的权限就会自动管理的。

**Comment by 0476** [comment]
> 首先，多分支流水线可以支持多个分支。我们假设有分支1，2，3。你说的指定分支，是希望只给分支1配置webhook吗？如果你不需要指定特定分支的话，对于GitHub而言，只要给你给定的账户有增加webhook的权限就会自动管理的。

如你所说，我是想给分支1增加webhook，对于分支2，3不接收webhook的请求，或者收到请求后不做任何处理。

**Comment by LinuxSuRen** [comment]
一种做法是，在多分支流水线中，增加正则表达式来过滤分支。
