### ISSUE TITLE
有没有好用的节假日api

### ISSUE THREAD

**Issue by yunweigo** [jenkins-zh/jenkins-zh.github.io#16]
有没有合适的节假日api接口， 通过判断当前是否为假期来确定是否执行Jenkins的建的操或者其他类型的操作。
如果没有合适的，可以通过什么方式实现此类功能。

**Comment by kylezhang** [comment]
感觉和jenkins没有关系.
可以看下这个apis能否给你一些启发https://www.sojson.com/api/lunar.html
