### ISSUE TITLE
在windows10上使用Jenkins配合docker和maven遇到的一个很奇怪的问题

### ISSUE THREAD

**Issue by Kitetop** [jenkins-zh/jenkins-zh.github.io#17]
我在Jenkinsfile里面定义了构建mysql容器，并且启动了这个容器，但是当我接下来运行mvn命令 
时想对java项目进行测试时，我的mysql容器却停止了。我在linux和windows上面使用的Jenkinsfile `都是一致的，唯一的区别就是我将里面的sh修改成了bat：
![Code_2019-09-26_11-29-32](https://user-images.githubusercontent.com/33886685/65656061-086f5e80-e051-11e9-98a7-c8755ec5fc78.png)
       Jenkins构建的输出：
![chrome_2019-09-26_11-32-21](https://user-images.githubusercontent.com/33886685/65656142-5b491600-e051-11e9-9ada-3ea30aa2d286.png)
        可以看到在运行了mvn命令之后，我的mysql容器是停止了的，但是如果我不在Jenkinsfile上进行mysql容器的构建，而是先在Windows上构建好这个容器，在Jenkinsfile上只对项目运行：【mvn clean package --file pom.xml】它又不会使得我的mysql容器停止。
        以上，就是我遇到的问题，感谢你的宝贵时间.

**Comment by LinuxSuRen** [comment]
如果把 `mvn clean` 去掉呢，是否 docker 还会停止

**Comment by Kitetop** [comment]
感谢你的提醒，刚才我尝试了，发现并不是因为运行mvn命令的问题，而是创建的镜像的问题。但是这也是很奇怪的，因为只有在Jenkinsfile上面运行创建image命令创建的镜像会有问题，而如果我直接在git bash里面输入同样的命令创建镜像，这个镜像就能够正常的构建我所需要的容器，下面是这个容器的报错信息，我在网上搜索了一些解决方案，但是很遗憾没有得到解决。非常抱歉，因为尝试解决这问题而让我回复你的信息晚了一些时间。
    下面是使用Jenkins创建的容器的日志报错信息：
![mintty_2019-09-26_13-45-28](https://user-images.githubusercontent.com/33886685/65662381-c7824480-e066-11e9-8b2a-ea07bc2490be.png)
     下面是我在git bash上使用同样的命令创建的容器，它并没有出现同样的错误：
![mintty_2019-09-26_13-47-42](https://user-images.githubusercontent.com/33886685/65662391-cd782580-e066-11e9-9c06-ddb9225ea34d.png)

**Comment by Kitetop** [comment]
好像这个问题并不止我一个人遇到，还是有其他人也遇到过的，不知道这是不是一个bug，或者说在Windows上面使用docker，Jenkins需要额外配置什么呢？
[同样的问题](https://stackoverflow.com/questions/57366007/standard-init-linux-go211-exec-user-process-caused-no-such-file-or-directory)

**Comment by LinuxSuRen** [comment]
你的 Jenkins 节点和手动测试的环境完全一样吗？

**Comment by Kitetop** [comment]
> 你的 Jenkins 节点和手动测试的环境完全一样吗？

一样的，都是同一台机器，Jenkinsfile上的agent指明的就是本机

**Comment by LinuxSuRen** [comment]
问题在于，那个容器是为什么退出的呢，能拿到错误信息吗

**Comment by Kitetop** [comment]
standard_init_linux.go:211: exec user process caused "no such file or directory"
这个就是导致容器退出的原因，现在我正在尝试使用doc2unix对容器的入口脚本进行转换，不知道能否解决这个问题。
但是，我奇怪的就是为啥我手动创建的是没有问题的，但是使用Jenkinsfile创建的容器就会有问题，是不是Jenkinsfile在执行这些命令的时候，会有不一样的处理机制呢？

**Comment by LinuxSuRen** [comment]
看看你的 Dockerfile 里是否有特殊的地方呢，另外，可以试试手动在 cmd 里，而不是git bash里构建docker

**Comment by Kitetop** [comment]
这个是我的Dockerfile文件：
![Code_2019-09-26_14-39-56](https://user-images.githubusercontent.com/33886685/65664570-2c8c6900-e06c-11e9-9787-d54b563ba9ed.png)
我尝试在cmd里面去构建我的镜像，发现它也是正常的，Dockfile倒没有什么特殊的地方。
我在Dockerfile上面新加了dos2unix，对入口脚本进行转化了一下在Jenkins上便能够使用，创建出正常镜像了。
