### ISSUE TITLE
jenkins新建job生成的job目录是750权限，怎么处理？

### ISSUE THREAD

**Issue by wokwong** [jenkins-zh/jenkins-zh.github.io#18]
jenkins新建job生成的job目录  为什么是750权限，不应该是755么？使用tomcat运行jenkins，root用户启动的

**Comment by LinuxSuRen** [comment]
建议给出一些上下文信息来，不然基本是无法确定具体原因。
另外，可以试试通过任务中执行的 shell 创建的文件的权限是什么。

**Comment by wokwong** [comment]
谢谢您的回答。不是报错，没有上下文呢，只是在使用过程中发现了这样的一个小问题，影响不大，只是在前端代码发布的时候出现了目录和文件权限问题，导致nginx不能读取文件。另外，任务重执行shell创建的文件权限是640，目录权限是750。

**Comment by LinuxSuRen** [comment]
感觉是由于父进程的配置导致的

**Comment by wokwong** [comment]
父进程就是root运行，实在不知道哪里有问题  哈哈

**Comment by LinuxSuRen** [comment]
可能是和 `umask` 的配置有关系。目前的问题是，我不知道如何复现你的问题。
