### ISSUE TITLE
请问此站点的发展路线是什么？我能帮上什么吗？

### ISSUE THREAD

**Issue by zacker330** [jenkins-zh/jenkins-zh.github.io#2]
希望能有帮得上忙的地方。

**Comment by LinuxSuRen** [comment]
这会是邮件组以外的另一个技术交流的地方，大家可以在每篇文章下面留言，例如：https://jenkins-zh.github.io/wechat/articles/2018-12-19-jenkins-survey/
另，QQ或者微信群，实际上不太适合做技术交流，因此也不会建群。
可能后面也会有一些教程或者案例分享之类的内容。当然，你有好的建议可以随时提出来。
