### ISSUE TITLE
jenkins Publish over SSH插件没有java环境变量

### ISSUE THREAD

**Issue by KongZouXiang** [jenkins-zh/jenkins-zh.github.io#20]
正常情况下远程是有环境变量的,使用jenkins ssh远程找不到环境变量,求解决方案

**Comment by LinuxSuRen** [comment]
这是有可能的，你可以在你的脚本里设置下环境变了，或者是在代理节点中增加设置。

**Comment by KongZouXiang** [comment]
> 这是有可能的，你可以在你的脚本里设置下环境变了，或者是在代理路由器中增加设置。

我手动加载了配置文件,经过测试,现在已经可以用了,非常感谢

**Comment by LinuxSuRen** [comment]
不客气，欢迎留言交流。
