### ISSUE TITLE
使用jenkins matlab模型生成代码集成过程比不用jenkins慢很多

### ISSUE THREAD

**Issue by woshiyushengzhou** [jenkins-zh/jenkins-zh.github.io#23]

**Comment by LinuxSuRen** [comment]
我对 matlab 不是很熟悉，可以多个一点上下文信息。

**Comment by woshiyushengzhou** [comment]
> 我对 matlab 不是很熟悉，可以多个一点上下文信息。

我们原来有一套将simulink模型生成C语言代码的脚本，之前整个运行耗时大概一个半小时，现在将脚本放到Jenkins上面运行耗时近6小时。

**Comment by LinuxSuRen** [comment]
这个理论上和 Jenkins 的关系是不大的，因为并不是 Jenkins 做这个事情，他是调度到其他的集群上做的，建议对比下节点的配置以及环境信息等。
