### ISSUE TITLE
Jenkins用户权限问题

### ISSUE THREAD

**Issue by knighttomato** [jenkins-zh/jenkins-zh.github.io#25]
1. Jenkins权限问题：
我在公司的Linux服务器安装了一个Jenkins，以root权限安装的，然后设置为Unix用户和组登录。大家使用已有的Unix用户名字即可登录了。但是登录后build任务还是root，这个要如何解决？

2. Jenkins credentials问题：
如果源码管理使用SVN，保存的Credentials 是不是可以直接使用？但是不同用户是不是看到的Credentials不同，有没有可能大家可以看到所有的Credentials？

**Comment by LinuxSuRen** [comment]
第二个问题，可能是和你保存凭据的位置有关系，如果是全局的，自然用户都能看到。

**Comment by knighttomato** [comment]
> 第二个问题，可能是和你保存凭据的位置有关系，如果是全局的，自然用户都能看到。

嗯嗯，多谢，我回去看下。
第一个问题遇到过吗？

**Comment by LinuxSuRen** [comment]
第一个问题，我有时间可以试试，没有这么玩儿过
