### ISSUE TITLE
Jenkins 安装updateCenter不可用

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-zh.github.io#32]
jdk：1.8
OS:  ubuntu 16.0.4
Jenkins启动方式: jar包启动方式
初始化启动会提示 Jenkins 为离线状态
updateCenter在获取的时候会报以下错误
![image](https://user-images.githubusercontent.com/20575981/69614808-c1144700-106e-11ea-941c-9bbd7f27a850.png)
测试：
- 1.测试清华源，不可用。
- 2.手动安装中文插件使用 Gitee 源，见注1，不可用

注1：
![image](https://user-images.githubusercontent.com/20575981/69615363-b0b09c00-106f-11ea-9f04-3092c010a055.png)

**Comment by LinuxSuRen** [comment]
根据上面的描述，可以推断和更新中心是没有关系的，建议仔细查找网络环境。
