### ISSUE TITLE
Jenkins国内镜像源更新报错

### ISSUE THREAD

**Issue by lazzicat** [jenkins-zh/jenkins-zh.github.io#39]
我已参照此处说明。

> https://community.jenkins-zh.cn/t/jenkins/26/18

使用了中文论坛的证书，并更新了升级站点的URL为：

> https://updates.jenkins-zh.cn/update-center.json

后，获取更新时仍报如下错误。我使用的是war包版本

`检查更新中心: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>（显示详情）</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: EMAILADDRESS=admin@jenkins-zh.com, CN=demo.com, OU=dev, O=vihoo, L=SZ, ST=GD, C=CN.<br> at sun.security.util.DisabledAlgorithmConstraints$KeySizeConstraint.permits(DisabledAlgorithmConstraints.java:817)<br> at sun.security.util.DisabledAlgorithmConstraints$Constraints.permits(DisabledAlgorithmConstraints.java:419)<br> at sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:167)<br> at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:326)<br> at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)<br>Caused: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: EMAILADDRESS=admin@jenkins-zh.com, CN=demo.com, OU=dev, O=vihoo, L=SZ, ST=GD, C=CN.<br> at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)<br> at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)<br> at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)<br> at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)<br> at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br> at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br> at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:88)<br> at hudson.model.UpdateSite.verifySignature(UpdateSite.java:264)<br> at hudson.model.UpdateSite.updateData(UpdateSite.java:228)<br> at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:208)<br> at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:203)<br> at hudson.PluginManager.checkUpdatesServer(PluginManager.java:1765)<br> at hudson.util.Retrier.start(Retrier.java:63)<br> at hudson.PluginManager.doCheckUpdatesServer(PluginManager.java:1736)<br> at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)<br> at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)<br> at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)<br> at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)<br> at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)<br> at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)<br> at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)<br> at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)<br> at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)<br> at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)<br> at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)<br> at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:169)<br> at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)<br> at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)<br> at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)<br> at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)<br> at org.kohsuke.stapler.Stapler.service(Stapler.java:238)<br> at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)<br> at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)<br> at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)<br> at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)<br> at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)<br> at hudson.plugins.locale.LocaleFilter.doFilter(LocaleFilter.java:42)<br> at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)<br> at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)<br> at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)<br> at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)<br> at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br> at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)<br> at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br> at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)<br> at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)<br> at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)<br> at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)<br> at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)<br> at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)<br> at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)<br> at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)<br> at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)<br> at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)<br> at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)<br> at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)<br> at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)<br> at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)<br> at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)<br> at org.eclipse.jetty.server.Server.handle(Server.java:500)<br> at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)<br> at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)<br> at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)<br> at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)<br> at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)<br> at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)<br> at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)<br> at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)<br> at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)<br> at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)<br> at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)<br> at java.lang.Thread.run(Thread.java:748)<br></pre> 时发生错误`

**Comment by LinuxSuRen** [comment]
`$JENKINS_HOME/war/WEB-INF/update-center-rootCAs/mirror-adapter.crt` 这个文件的内容是什么呢？

**Comment by lazzicat** [comment]
> `$JENKINS_HOME/war/WEB-INF/update-center-rootCAs/mirror-adapter.crt` 这个文件的内容是什么呢？

-----BEGIN CERTIFICATE-----
MIICcTCCAdoCCQD/jZ7AgrzJKTANBgkqhkiG9w0BAQsFADB9MQswCQYDVQQGEwJD
TjELMAkGA1UECAwCR0QxCzAJBgNVBAcMAlNaMQ4wDAYDVQQKDAV2aWhvbzEMMAoG
A1UECwwDZGV2MREwDwYDVQQDDAhkZW1vLmNvbTEjMCEGCSqGSIb3DQEJARYUYWRt
aW5AamVua2lucy16aC5jb20wHhcNMTkxMTA5MTA0MDA5WhcNMjIxMTA4MTA0MDA5
WjB9MQswCQYDVQQGEwJDTjELMAkGA1UECAwCR0QxCzAJBgNVBAcMAlNaMQ4wDAYD
VQQKDAV2aWhvbzEMMAoGA1UECwwDZGV2MREwDwYDVQQDDAhkZW1vLmNvbTEjMCEG
CSqGSIb3DQEJARYUYWRtaW5AamVua2lucy16aC5jb20wgZ8wDQYJKoZIhvcNAQEB
BQADgY0AMIGJAoGBAN+6jN8rCIjVkQ0Q7ZbJLk4IdcHor2WdskOQMhlbR0gOyb4g
RX+CorjDRjDm6mj2OohqlrtRxLGYxBnXFeQGU7wWjQHyfKDghtP51G/672lXFtzB
KXukHByHjtzrDxAutKTdolyBCuIDDGJmRk+LavIBY3/Lxh6f0ZQSeCSJYiyxAgMB
AAEwDQYJKoZIhvcNAQELBQADgYEAD92l26PoJcbl9GojK2L3pyOQjeeDm/vV9e3R
EgwGmoIQzlubM0mjxpCz1J73nesoAcuplTEps/46L7yoMjptCA3TU9FZAHNQ8dbz
a0vm4CF9841/FIk8tsLtwCT6ivkAi0lXGwhX0FK7FaAyU0nNeo/EPvDwzTim4XDK
9j1WGpE=
-----END CERTIFICATE-----

**Comment by LinuxSuRen** [comment]
证书文件是没问题的

**Comment by lazzicat** [comment]
终于找到原因和解决的方法了。我是centos 8 ，默认的加密策略对证书是1024长度时会不兼容，需要将加密策略设置为legacy才行。使用root权限修改加密策略后，重启Jenkins成功解决问题。
[解决方案来源是：https://issues.shibboleth.net/jira/browse/OSJ-279](https://issues.shibboleth.net/jira/browse/OSJ-279)
[此处有关于加密策略的详细说明：https://www.redhat.com/en/blog/consistent-security-crypto-policies-red-hat-enterprise-linux-8](https://www.redhat.com/en/blog/consistent-security-crypto-policies-red-hat-enterprise-linux-8)
> 证书文件是没问题的

**Comment by tonghu007** [comment]
如果在docker中跑jenkins呢，要怎么处理这个问题呢

**Comment by liixao** [comment]
@tonghu007 宿主机设置
