### ISSUE TITLE
build project, and show Sorry, Page Not Found

### ISSUE THREAD

**Issue by JackHuang0801** [jenkins-zh/jenkins-zh.github.io#46]
![微信截图_20201119162003](https://user-images.githubusercontent.com/12622057/99639953-444e5a00-2a83-11eb-8801-01c362ec57fd.png)

**Comment by JackHuang0801** [comment]
![微信截图_20201119162029](https://user-images.githubusercontent.com/12622057/99640080-6811a000-2a83-11eb-9e05-369d0a4b6c18.png)

**Comment by JackHuang0801** [comment]
![微信截图_20201119162320](https://user-images.githubusercontent.com/12622057/99640216-8ecfd680-2a83-11eb-8255-b6d90518d88c.png)

**Comment by LinuxSuRen** [comment]
可以贴一下相关信息：
* Jenkins 的版本
* 流水线脚本
* 报错时 Jenkins 控制台的错误信息

**Comment by JackHuang0801** [comment]
1.版本尝试过2.235.3、2.249.3和2.267
2.流水线脚本不知道哪里可以导出，哈哈
3.后台日志，我查过 /var/log/jenkins/jenkins.log，没有报错信息

**Comment by JackHuang0801** [comment]
怀疑是Build With Parameters这个插件，改用指定分支写死来build就可以（这种方式不会跳转url -> xxx/build?delay=0sec）
下面的是这个插件的配置：
![微信截图_20201120140808](https://user-images.githubusercontent.com/12622057/99765564-4b846f00-2b3a-11eb-9260-4c8f6e007416.png)
