### ISSUE TITLE
withEnv(['JENKINS_NODE_COOKIE=dontkillme']) {}  2.277.1版本不生效

### ISSUE THREAD

**Issue by chenqiguang** [jenkins-zh/jenkins-zh.github.io#53]
在版本2.121.1 流水线pipeline里面使用dontkillme是有效果的，如下图
![image](https://user-images.githubusercontent.com/24667581/112565784-b8758180-8e18-11eb-96a7-126b59165224.png)

但是在版本2.277.1 流水线pipeline里面使用dontkillme去没有效果，shell执行结束后，仍然会杀死子线程
![image](https://user-images.githubusercontent.com/24667581/112565849-dd69f480-8e18-11eb-8811-b11b09b98d4f.png)

请问一下是高版本语法变了吗？该怎么写呢

**Comment by LinuxSuRen** [comment]
这本就是一种非常规的做法，你如果想要启动守护进程，就应该用启动服务的方式。

**Comment by chenqiguang** [comment]
请问一下这个应该怎么弄呢？ 我之前也试过使用buildId之类的，还改过配置文件好像都不行

**Comment by LinuxSuRen** [comment]
那要看你启动什么

**Comment by chenqiguang** [comment]
我现在是要启动一个java程序，截图里面的shell就是启动脚本的

**Comment by LinuxSuRen** [comment]
那你可以搜索下，如何制作Linux服务

**Comment by chenqiguang** [comment]
我直接在服务器里面执行脚本启动都是好的，可以启动，但是jenkins走流水线就会被杀死子线程

**Comment by LinuxSuRen** [comment]
流水线结束后需要释放进程资源，所以会把子进程关闭，这是正常的逻辑。你可以参考我上面的建议
