### ISSUE TITLE
关于Publish over SSH插件使用出现的错误（求解答）

### ISSUE THREAD

**Issue by kktao11** [jenkins-zh/jenkins-zh.github.io#56]
首先在提问之前我是在各大知识网站上是有搜索并且尝试过解决方案，都行不通，所以来到Jenkins中文社区请求协助。正常的是我新增一个SSH Server Name填自己的服务名(任意了)，host也是正确的 可以ping通并且开放了22端口，并且打开了SSHD服务，Remote Directory地址我填的是 / ，这里说清楚一点就是我的SSH公钥也是有复制到authorized_keys里面的，以上配置还是不能正确TEST，后面我点进了高级Passphrase / Password 我填的是服务器密码，我的Passphrase 设置的跟服务器的密码也是一样的，key的话填的是私钥，然后去 TEST 也是一样
附上错误代码：Failed to connect or change directory，
jenkins.plugins.publish_over.BapPublisherException: Failed to connect and initialize SSH connection. Message: [Failed to connect session for config [kktao]. Message [java.net.ConnectException: Connection timed out (Connection timed out)]]
上面说我目录错误，我寻思看了看也没问题啊，而且我是根据我朋友的来配的，他可以,我不可以，甚至他只配了Name、Hostname、Username、Remote Directory都可以Success,求大神解答呀~0.0.0.0.0.0.0.0.0

**Comment by LinuxSuRen** [comment]
我没有用过这个插件，但是，没有其他的错误日志了吗？
