### ISSUE TITLE
Jenkins 中文社区 and Shenzhen JUG

### ISSUE THREAD

**Issue by paulvi** [jenkins-zh/jenkins-zh.github.io#6]
大家好

Hello, my name is Paul Verest 微保罗
I have been active within developers meetings and opensource, and started Shenzhen Java User Group
http://szjug.github.io/

I am so sad I missed [Jenkins User Conference China(JUCC) ](https://jenkins.io/blog/2019/01/09/jenkins-user-conference-china-shenzhen-update/) and could not share within JUG members.
So can we cooperate for future events, or actually start preparing for next one.

Just learned from 赵晓杰(Rick) @linuxsuren post in https://jenkins.io/blog/2019/02/05/jenkins-new-year-in-china/ .

**Comment by LinuxSuRen** [comment]
Hi Paul,

Glad to know you. You can find us on this Gitter channel. https://gitter.im/jenkinsci/chinese-localization-sig

I'd like to discuss more details about cooperation.

**Comment by paulvi** [comment]
OK
