### ISSUE TITLE
存在很多 djenkins.model.jenkisn.slaveagentport

### ISSUE THREAD

**Issue by Sanmejie** [jenkins-zh/jenkins-zh.github.io#63]
hi，在`https://community.jenkins-zh.cn/t/java-duser-home-var-jenkins-home-djenkins-model-jenkisn-slaveagentport-50000/964`中文社区提问没有回答尝试在这里再试下。 

![image](https://user-images.githubusercontent.com/40269911/131252434-29eda641-c899-4b34-adb8-c16f9bce7dd3.png)

问题一：
java -duser.home=/var/jenkins_home -djenkins.model.jenkisn.slaveagentport=50000是什么进程？jenkins没有运行job情况，节点都下线了怎么还有这么多？
问题二：
为什么jenkins这么占虚拟内存？
问题三：
今天在jenkins发现好多挖矿job ，怎么能预防入侵？

**Comment by LinuxSuRen** [comment]
看起来你的机器中有脚本之类的，启动了很多的 Jenkins

挖矿脚本和Jenkins没有关系，检查下你的系统漏洞吧，例如：弱口令、端口开放

**Comment by Sanmejie** [comment]
> 看起来你的机器中有脚本之类的，启动了很多的 Jenkins
> 
> 挖矿脚本和Jenkins没有关系，检查下你的系统漏洞吧，例如：弱口令、端口开放

感谢回答！已经更改密码。   容器是通过这个命令起来的，   `docker run -u root -d -p23:22 -p 8080:8080 -p 50001:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins/jenkins:lts-jdk11`  并且查看了运行中容器只有一个jenkins实例

**Comment by LinuxSuRen** [comment]
检查下是不是有很多Jenkins的容器呢

**Comment by Sanmejie** [comment]
> 检查下是不是有很多Jenkins的容器呢

确认了 只有一个
