### ISSUE TITLE
The https://jenkins-zh.github.io/ site has link to Jenkins X

### ISSUE THREAD

**Issue by paulvi** [jenkins-zh/jenkins-zh.github.io#7]
It looks like https://jenkins-zh.github.io/ is cloned from Jenkins X site https://jenkins-x.io/

and many links that should be updated

**Comment by LinuxSuRen** [comment]
Yes, it is.

**Comment by paulvi** [comment]
I wonder are guys from Jenkins 中文社区 are contributers to Jenkins X.
Or was it just the most suitable site template ....

**Comment by LinuxSuRen** [comment]
I'm the contributor of the Jenkins X. I just don't have so much energy to change all links. But it'll be changed eventually.

**Comment by paulvi** [comment]
OK, Jenkins X is written in Go,  
that explains why Java User Group might have been under-presented on China Jenkins User Conference
